version: "3.8"

services:
  app:
    build: .
    container_name: erpgo_app
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      APP_ENV: production

  db:
    image: mysql:5.7
    container_name: erpgo_db
    restart: always
    environment:
      MYSQL_DATABASE: erpgo
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
